apiVersion: v1
kind: Service
metadata:
  name: contoso-names-service
  namespace: contoso-names
spec:
  type: ClusterIP
  selector:
    app: contoso-names-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80